# Generated by Django 4.1.1 on 2022-11-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('addres', models.CharField(max_length=200)),
                ('instagram', models.URLField(max_length=250)),
                ('linkeding', models.URLField(max_length=250)),
                ('facebook', models.URLField(max_length=250)),
            ],
            options={
                'verbose_name': 'Sazlamalar',
                'verbose_name_plural': 'Sazlamalar',
            },
        ),
    ]
