# Generated by Django 4.1.1 on 2022-11-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_about_contactus_services_workour'),
    ]

    operations = [
        migrations.AddField(
            model_name='workour',
            name='title_addres',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
